# Generated by Django 4.2.10 on 2024-03-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brake_type',
            field=models.CharField(blank=True, choices=[('Caliper', 'Caliper'), ('V-Brake', 'V-Brake'), ('Cantilever', 'Cantilever'), ('Mechanical Disc', 'Mechanical Disc'), ('Hydraulic Disc', 'Hydraulic Disc')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, choices=[('XS', '17in'), ('S', '17-19in'), ('M', '19-22in'), ('L', '21-23in'), ('XL', '>23in')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tire_size',
            field=models.CharField(blank=True, choices=[('10in', '10in'), ('12in', '12in'), ('14in', '14in'), ('16in', '16in'), ('20in', '20in'), ('24in', '24in'), ('26in', '26in'), ('27.5in', '27.5in')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
