# Generated by Django 4.2.10 on 2024-03-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_brake_type_item_material_item_tire_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='frame_size',
            field=models.CharField(blank=True, choices=[('XS', '17in'), ('S', '17-19in'), ('M', '19-22in'), ('L', '21-23in'), ('XL', '>23in')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, choices=[('Steel', 'Steel'), ('Aluminum/Alloy', 'Aluminum/Alloy'), ('Carbon Fiber', 'Carbon Fiber'), ('Titanium', 'Titanium')], max_length=20, null=True),
        ),
    ]
