# Generated by Django 4.2.10 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_frame_size_alter_item_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('Children Bike', 'Children Bike'), ('Foldable Bike', 'Foldable Bike'), ('City Bike', 'City Bike'), ('Mountain Bike', 'Mountain Bike'), ('Touring Bike', 'Touring Bike')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, choices=[('Steel', 'Steel'), ('Aluminum/Foldable Bike', 'Aluminum/Alloy'), ('Carbon City Bike', 'Carbon Fiber'), ('Titanium', 'Titanium')], max_length=22, null=True),
        ),
    ]
