# Generated by Django 4.2.10 on 2024-04-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_item_image_2_item_image_3_item_image_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/item_images/default_photo.jpg', upload_to='item_images'),
        ),
    ]
