# Generated by Django 4.2.10 on 2024-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tire_size',
            field=models.CharField(blank=True, choices=[('10in', '10in'), ('12in', '12in'), ('14in', '14in'), ('16in', '16in'), ('18in', '18in'), ('20in', '20in'), ('22in', '22in'), ('24in', '24in'), ('26in', '26in'), ('27.5in', '27.5in'), ('29in', '29in')], max_length=8, null=True),
        ),
    ]
