# Generated by Django 4.2.10 on 2024-04-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_item_image_alter_item_tire_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='frame_size',
            field=models.CharField(blank=True, choices=[('XS', '17in'), ('S', '17-19in'), ('M', '19-21in'), ('L', '21-23in'), ('XL', '>23in')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, choices=[('Steel', 'Steel'), ('Aluminum/Alloy', 'Aluminum/Alloy'), ('Carbon Fiber', 'Carbon Fiber'), ('Titanium', 'Titanium')], max_length=22, null=True),
        ),
    ]
