# Generated by Django 4.2.10 on 2024-05-03 08:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_item_frame_size_alter_item_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
