# Generated by Django 4.2.10 on 2024-05-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
