# Generated by Django 4.2.10 on 2024-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_remove_item_frame_size_item_drivetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
