# Generated by Django 4.2.10 on 2024-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('Nil', 'Nil'), ('6-speed', '6-speed'), ('7-speed', '7-speed'), ('8-speed', '8-speed'), ('9-speed', '9-speed'), ('10-speed', '10-speed'), ('11-speed', '11-speed'), ('12-speed', '12-speed'), ('>12-speed', '>12-speed')], max_length=9, null=True),
        ),
    ]
