# Generated by Django 4.2.10 on 2024-02-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="created",
            new_name="created_on",
        ),
    ]
