# Generated by Django 4.2.10 on 2024-05-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_content_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/background1.jpg', upload_to='images/'),
        ),
    ]
