# Generated by Django 4.2.5 on 2023-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='location',
            field=models.CharField(default='Bishan', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold')], default='Available', max_length=20),
        ),
    ]
