# Generated by Django 4.2.5 on 2023-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bike_location_bike_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
