# Generated by Django 4.2.5 on 2023-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_alter_bike_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='main_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
