# Generated by Django 4.2.5 on 2023-12-06 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0006_alter_bike_main_photo"),
    ]

    operations = []


from django.db import migrations, models


def set_default_main_photo(apps, schema_editor):
    Bike = apps.get_model("bikes", "Bike")
    # Set an empty string as the default value for main_photo
    Bike.objects.filter(main_photo__isnull=True).update(main_photo="")


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0006_alter_bike_main_photo"),
    ]

    operations = [
        migrations.RunPython(set_default_main_photo),
    ]
